### ISSUE TITLE
Proposal for generalized tracers

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/CCL#627] opened 2019-04-19 06:41 UTC
Here's a proposal for the implementation of generalized tracers (the second task in issue #511). Comments from @elisachisari @elikrause @jablazek @tilmantroester @beckermr @slosar and/or @joezuntz would be useful. Apologies for the long issue!

### Setup and definitions
Start by interpreting a tracer as a given projected quantity in the sky:
<a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{100}&space;u(\hat{\bf&space;n})=\int&space;d\chi\,W_u(\chi)\,U(\chi\hat{\bf&space;n},t(\chi))" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dpi{100}&space;u(\hat{\bf&space;n})=\int&space;d\chi\,W_u(\chi)\,U(\chi\hat{\bf&space;n},t(\chi))" title="u(\hat{\bf n})=\int d\chi\,W_u(\chi)\,U(\chi\hat{\bf n},t(\chi))" /></a>
here <a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{100}&space;u(\hat{\bf&space;n})" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dpi{100}&space;u(\hat{\bf&space;n})" title="u(\hat{\bf n})" /></a> is the projected quantity, <a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{150}&space;U({\bf&space;x},t)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dpi{100}&space;U({\bf&space;x},t)" title="U({\bf x},t)" /></a> is the corresponding 3D quantity and <a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{100}&space;W_u(\chi)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dpi{100}&space;W_u(\chi)" title="W_u(\chi)" /></a> is what I'll call the tracer's *radial kernel*. This setup should be enough to describe the vast majority of 2D quantities we'll be interested in in DESC and future CMB/radio experiments (see one exception below).

In this case, the angular power spectrum of <a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{100}&space;u(\hat{\bf&space;n})" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dpi{100}&space;u(\hat{\bf&space;n})" title="u(\hat{\bf n})" /></a> crossed with a similar projected quantity <a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{100}&space;v(\hat{\bf&space;n})" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dpi{100}&space;v(\hat{\bf&space;n})" title="v(\hat{\bf n})" /></a> will be given by:
<a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{100}&space;C^{uv}_\ell&space;=&space;\frac{2}{\pi}\,\int&space;d\chi&space;d\chi'&space;dk&space;k^2&space;P_{UV}(k,\chi,\chi')\,W_u(\chi)\,j_\ell(k\chi)\,W_v(\chi')\,j_\ell(k\chi')" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dpi{100}&space;C^{uv}_\ell&space;=&space;\frac{2}{\pi}\,\int&space;d\chi&space;d\chi'&space;dk&space;k^2&space;P_{UV}(k,\chi,\chi')\,W_u(\chi)\,j_\ell(k\chi)\,W_v(\chi')\,j_\ell(k\chi')" title="C^{uv}_\ell = \frac{2}{\pi}\,\int d\chi d\chi' dk k^2 P_{UV}(k,\chi,\chi')\,W_u(\chi)\,j_\ell(k\chi)\,W_v(\chi')\,j_\ell(k\chi')" /></a>
where <a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{100}&space;P_{UV}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dpi{100}&space;P_{UV}" title="P_{UV}" /></a> is the power spectrum of the two 3D quantities:
<a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{100}&space;\left\langle&space;U({\bf&space;k},t(\chi))&space;V^*({\bf&space;q},t(\chi'))\right\rangle=\delta({\bf&space;k}-{\bf&space;q})P_{UV}(k,\chi,\chi')" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dpi{100}&space;\left\langle&space;U({\bf&space;k},t(\chi))&space;V^*({\bf&space;q},t(\chi'))\right\rangle=\delta({\bf&space;k}-{\bf&space;q})P_{UV}(k,\chi,\chi')" title="\left\langle U({\bf k},t(\chi)) V^*({\bf q},t(\chi'))\right\rangle=\delta({\bf k}-{\bf q})P_{UV}(k,\chi,\chi')" /></a>,
and I haven't applied the Limber approximation yet.

Applying it, we obtain:
<a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{100}&space;C^{uv}_\ell&space;=&space;\frac{2}{2\ell&plus;1}\int_{k_{\rm&space;min}}^{k_{\rm&space;max}}&space;dk\,P_{UV}\left(k,\chi=\chi'=\frac{\ell&plus;1/2}{k}\right)\,W_u\left(\frac{\ell&plus;1/2}{k}\right)\,W_v\left(\frac{\ell&plus;1/2}{k}\right)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dpi{100}&space;C^{uv}_\ell&space;=&space;\frac{2}{2\ell&plus;1}\int_{k_{\rm&space;min}}^{k_{\rm&space;max}}&space;dk\,P_{UV}\left(k,\chi=\chi'=\frac{\ell&plus;1/2}{k}\right)\,W_u\left(\frac{\ell&plus;1/2}{k}\right)\,W_v\left(\frac{\ell&plus;1/2}{k}\right)" title="C^{uv}_\ell = \frac{2}{2\ell+1}\int_{k_{\rm min}}^{k_{\rm max}} dk\,P_{UV}\left(k,\chi=\chi'=\frac{\ell+1/2}{k}\right)\,W_u\left(\frac{\ell+1/2}{k}\right)\,W_v\left(\frac{\ell+1/2}{k}\right)" /></a>
or, in terms of <a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{100}&space;\chi" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dpi{100}&space;\chi" title="\chi" /></a>:
<a href="https://www.codecogs.com/eqnedit.php?latex=C^{uv}_\ell&space;=&space;\int_{\chi_{\rm&space;min}}^{\chi_{\rm&space;max}}&space;d\chi\,P_{UV}\left(k=\frac{\ell&plus;1/2}{\chi},\chi\right)\,\frac{W_u(\chi)\,W_v(\chi)}{\chi^2}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?C^{uv}_\ell&space;=&space;\int_{\chi_{\rm&space;min}}^{\chi_{\rm&space;max}}&space;d\chi\,P_{UV}\left(k=\frac{\ell&plus;1/2}{\chi},\chi\right)\,\frac{W_u(\chi)\,W_v(\chi)}{\chi^2}" title="C^{uv}_\ell = \int_{\chi_{\rm min}}^{\chi_{\rm max}} d\chi\,P_{UV}\left(k=\frac{\ell+1/2}{\chi},\chi\right)\,\frac{W_u(\chi)\,W_v(\chi)}{\chi^2}" /></a>.

### Transfer functions and ell-factors
OK, so using the notation above, and since we have already implemented the generalized power spectrum ([`Pk2D`](https://github.com/LSSTDESC/CCL/blob/master/pyccl/p2d.py)) objects, a very minimal implementation of a generalized tracer would be to define a tracer as an object that essentially carries around a radial kernel <a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{100}&space;W_u(\chi)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dpi{100}&space;W_u(\chi)" title="W_u(\chi)" /></a>, and users would have to define those on the one hand, and the corresponding <a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{100}&space;P_{UV}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dpi{100}&space;P_{UV}" title="P_{UV}" /></a> for any pair of tracers they want to correlate as a `Pk2D` object, and then pass them to `ccl.angular_cl`. I think this is a good approach in certain cases (e.g. this is what we're doing for halo-model power spectra in the HSC analysis project). In many very common situations, however, this is going to be a bit impractical.

In many situations, the 3D quantities associated to our tracers will be related to a fundamental quantity such as the matter overdensity <a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{100}&space;\delta_M" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dpi{100}&space;\delta_M" title="\delta_M" /></a> through a simple linear *transfer function* <a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{100}&space;T_U(k,z)=U({\bf&space;k},z)/\delta_M({\bf&space;k},z)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dpi{100}&space;T_U(k,z)=U({\bf&space;k},z)/\delta_M({\bf&space;k},z)" title="T_U(k,z)=U({\bf k},z)/\delta_M({\bf k},z)" /></a>. Furthermore, in many cases these are factorizable <a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{100}&space;T_U(k,z)=K_U(k)Z_U(z)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dpi{100}&space;T_U(k,z)=K_U(k)Z_U(z)" title="T_U(k,z)=K_U(k)Z_U(z)" /></a>, so that the 3D power spectrum is <a href="https://www.codecogs.com/eqnedit.php?latex=P_{UV}(k,z)=T_U(k,z)T_V(k,z)P_M(k,z)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?P_{UV}(k,z)=T_U(k,z)T_V(k,z)P_M(k,z)" title="P_{UV}(k,z)=T_U(k,z)T_V(k,z)P_M(k,z)" /></a>.
A few examples:

- Galaxy clustering with linear bias: <a href="https://www.codecogs.com/eqnedit.php?latex=W_g(z)=H(z)\frac{dN}{dz};\hspace{6pt}&space;T_g(k,z)=b(z);\hspace{6pt}&space;K_g(k)=1;\hspace{6pt}&space;Z_g(z)=b(z)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?W_g(z)=H(z)\frac{dN}{dz};\hspace{6pt}&space;T_g(k,z)=b(z);\hspace{6pt}&space;K_g(k)=1;\hspace{6pt}&space;Z_g(z)=b(z)" title="W_g(z)=H(z)\frac{dN}{dz};\hspace{6pt} T_g(k,z)=b(z);\hspace{6pt} K_g(k)=1;\hspace{6pt} Z_g(z)=b(z)" /></a>.
- Cosmic shear: <a href="https://www.codecogs.com/eqnedit.php?latex=W_\gamma(\chi)=\frac{W_L(\chi)}{\chi};\hspace{6pt}&space;T_\gamma=-\frac{T_{\psi&plus;\phi}}{2};\hspace{6pt}&space;K_\gamma(k)=\frac{1}{k^2};\hspace{6pt}&space;Z_\gamma(z)=\frac{3H_0^2\Omega_M}{2a}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?W_\gamma(\chi)=\frac{W_L(\chi)}{\chi};\hspace{6pt}&space;T_\gamma=-\frac{T_{\psi&plus;\phi}}{2};\hspace{6pt}&space;K_\gamma(k)=\frac{1}{k^2};\hspace{6pt}&space;Z_\gamma(z)=\frac{3H_0^2\Omega_M}{2a}" title="W_\gamma(\chi)=\frac{W_L(\chi)}{\chi};\hspace{6pt} T_\gamma=-\frac{T_{\psi+\phi}}{2};\hspace{6pt} K_\gamma(k)=\frac{1}{k^2};\hspace{6pt} Z_\gamma(z)=\frac{3H_0^2\Omega_M}{2a}" /></a>.
- CMB lensing: <a href="https://www.codecogs.com/eqnedit.php?latex=W_\kappa(\chi)=\frac{\chi_{*}-\chi}{\chi\chi_*};\hspace{6pt}&space;T_\kappa=-\frac{T_{\psi&plus;\phi}}{2};\hspace{6pt}&space;K_\kappa(k)=\frac{1}{k^2};\hspace{6pt}&space;Z_\kappa(z)=\frac{3H_0^2\Omega_M}{2a}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?W_\kappa(\chi)=\frac{\chi_{*}-\chi}{\chi\chi_*};\hspace{6pt}&space;T_\kappa=-\frac{T_{\psi&plus;\phi}}{2};\hspace{6pt}&space;K_\kappa(k)=\frac{1}{k^2};\hspace{6pt}&space;Z_\kappa(z)=\frac{3H_0^2\Omega_M}{2a}" title="W_\kappa(\chi)=\frac{\chi_{*}-\chi}{\chi\chi_*};\hspace{6pt} T_\kappa=-\frac{T_{\psi+\phi}}{2};\hspace{6pt} K_\kappa(k)=\frac{1}{k^2};\hspace{6pt} Z_\kappa(z)=\frac{3H_0^2\Omega_M}{2a}" /></a>.
- IAs within the L-NLA model: <a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{100}&space;W_I(\chi)=\frac{dN}{dz}H;\hspace{6pt}&space;K_I=\frac{1}{k^2};\hspace{6pt}&space;Z_I(z)=\frac{b_{\rm&space;IA}(z)}{\chi(z)}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dpi{100}&space;W_I(\chi)=\frac{dN}{dz}H;\hspace{6pt}&space;K_I=\frac{1}{k^2};\hspace{6pt}&space;Z_I(z)=\frac{b_{\rm&space;IA}(z)}{\chi(z)}" title="W_I(\chi)=\frac{dN}{dz}H;\hspace{6pt} K_I=\frac{1}{k^2};\hspace{6pt} Z_I(z)=\frac{b_{\rm IA}(z)}{\chi(z)}" /></a>
- Magnification bias: <a href="https://www.codecogs.com/eqnedit.php?latex=W_\mu(\chi)=\frac{W_M(\chi)}{\chi};\hspace{6pt}&space;T_\mu=T_{\psi&plus;\phi};\hspace{6pt}&space;K_\mu(k)=\frac{1}{k^2};\hspace{6pt}&space;Z_\mu(z)=-\frac{3H_0^2\Omega_M}{a}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?W_\mu(\chi)=\frac{W_M(\chi)}{\chi};\hspace{6pt}&space;T_\mu=T_{\psi&plus;\phi};\hspace{6pt}&space;K_\mu(k)=\frac{1}{k^2};\hspace{6pt}&space;Z_\mu(z)=-\frac{3H_0^2\Omega_M}{a}" title="W_\mu(\chi)=\frac{W_M(\chi)}{\chi};\hspace{6pt} T_\mu=T_{\psi+\phi};\hspace{6pt} K_\mu(k)=\frac{1}{k^2};\hspace{6pt} Z_\mu(z)=-\frac{3H_0^2\Omega_M}{a}" /></a>

Here
<a href="https://www.codecogs.com/eqnedit.php?latex=W_L(\chi)=\int_z^\infty&space;dz'\,\frac{dN}{dz'}\frac{\chi(z')-\chi(z))}{\chi(z')}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?W_L(\chi)=\int_z^\infty&space;dz'\,\frac{dN}{dz'}\frac{\chi(z')-\chi(z))}{\chi(z')}" title="W_L(\chi)=\int_z^\infty dz'\,\frac{dN}{dz'}\frac{\chi(z')-\chi(z))}{\chi(z')}" /></a>
and
<a href="https://www.codecogs.com/eqnedit.php?latex=W_M(\chi)=\int_z^\infty&space;dz'\,\frac{dN}{dz'}\frac{2-5s(z')}{2}\frac{\chi(z')-\chi(z))}{\chi(z')}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?W_M(\chi)=\int_z^\infty&space;dz'\,\frac{dN}{dz'}\frac{2-5s(z')}{2}\frac{\chi(z')-\chi(z))}{\chi(z')}" title="W_M(\chi)=\int_z^\infty dz'\,\frac{dN}{dz'}\frac{2-5s(z')}{2}\frac{\chi(z')-\chi(z))}{\chi(z')}" /></a>.

Note that there is an obvious degeneracy between the radial kernel and the redshift-dependent part of the transfer function, but it'll be up to the user to decide where to put things.

Finally, some of these tracers take an additional multiplicative factor depending only on <a href="https://www.codecogs.com/eqnedit.php?latex=\ell" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\ell" title="\ell" /></a>, coming from different types of second-order derivatives of the angles. I'll call these factors <a href="https://www.codecogs.com/eqnedit.php?latex=f_\ell" target="_blank"><img src="https://latex.codecogs.com/gif.latex?f_\ell" title="f_\ell" /></a>. For the tracers above these are:
<a href="https://www.codecogs.com/eqnedit.php?latex=f^g_\ell=f^I_\ell=1" target="_blank"><img src="https://latex.codecogs.com/gif.latex?f^g_\ell=f^I_\ell=1" title="f^g_\ell=f^I_\ell=1" /></a>
<a href="https://www.codecogs.com/eqnedit.php?latex=f^\kappa_\ell=f^\mu_\ell=\ell(\ell&plus;1)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?f^\kappa_\ell=f^\mu_\ell=\ell(\ell&plus;1)" title="f^\kappa_\ell=f^\mu_\ell=\ell(\ell+1)" /></a>
and
<a href="https://www.codecogs.com/eqnedit.php?latex=f^\gamma_\ell=\sqrt{\frac{(\ell&plus;2)!}{(\ell-2)!}}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?f^\gamma_\ell=\sqrt{\frac{(\ell&plus;2)!}{(\ell-2)!}}" title="f^\gamma_\ell=\sqrt{\frac{(\ell+2)!}{(\ell-2)!}}" /></a>.

### Concrete proposal for generalized tracers
A generalized tracer will be defined by three quantities:
- A radial kernel <a href="https://www.codecogs.com/eqnedit.php?latex=W_u(\chi)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?W_u(\chi)" title="W_u(\chi)" /></a>. I.e. a 1D function of the radial coordinates (distance or redshift). This will be provided as a python function or as a pair of arrays to be interpolated.
- A transfer function <a href="https://www.codecogs.com/eqnedit.php?latex=T_u(k,z)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?T_u(k,z)" title="T_u(k,z)" /></a>. I.e. a 2D function of k and z. This will be provided as a python function or as a set of arrays. We will also support the case where this function is factorizable, since initializing 1D splines is much faster than 2D ones. By default, this transfer function will be just 1.
- An ell-dependent prefactor <a href="https://www.codecogs.com/eqnedit.php?latex=f^u_\ell" target="_blank"><img src="https://latex.codecogs.com/gif.latex?f^u_\ell" title="f^u_\ell" /></a>.
- Tracers will also have an addition operation so you can generate  new tracers by adding basic ones. E.g. our current "number counts" tracer is an addition of the galaxy density, magnification and RSD tracers. Our "weak lensing" tracer is an addition of the shear and IA tracers above.
- We will provide functions to initialize the set of basic tracers that are currently supported in the library (number counts, weak lensing and CMB lensing) without breaking the python API.

I think, in combination with the generalized power spectrum structures currently implemented in CCL, this covers the vast majority of scenarios we're envisaging (the current implementation, PT and halo model). One case that is not covered by this is the RSD contribution, but we can create one special tracer for that.

Thoughts?

**Comment by beckermr** [comment] 2019-04-19 15:23
I’ll need to go through the math in more detail when I am not on my phone. However the general scheme and api looks fine. My only ask is that we think now about how to do the RSD stuff with an api that is the same or as close as possible. I don’t want to break our apis or have to make a new one yet again.

**Comment by damonge** [comment] 2019-04-19 16:01
Thanks Matt. I agree and I think it's actually doable: you just add a flag to all tracers that determine what order a derivative of the Bessel functions they should be integrated with (it's zero with most tracers, but 2 for RSD - and 1 for some irrelevant relativistic effects I haven't added above).

Oh, and I should also add, my plan is for most of this to live in python and for the C components to be mostly a bunch of containers for splines and integration functions

**Comment by beckermr** [comment] 2019-04-19 16:20
Sounds good. I think that this is a place where an almost pure c implementation might be preferable. We probably should avoid c calling python functions if we can.

**Comment by damonge** [comment] 2019-04-19 20:18
I want the infrastructure to be there, but for the specifics to live in python (e.g. there'll be `ClTracer` structures in C holding generic implementations of all of the above, but the implementation of e.g. linear bias and `NumberCountTracer` objects will only live in python)

**Comment by beckermr** [comment] 2019-04-19 22:15
Yup. We don't need to have a specific linear bias model in this repo. We can basically leave the API we have now in place where the function only accepts an array in z.

**Comment by slosar** [comment] 2019-04-20 11:38
This is great, really really great.
A few thoughts:
 * The derivative of Bessel function is a very good solution that puts RSD on the same footing. And we might eventually try to do some GR correction
 * This is all for scalar functions, yes? Lensing here is E-modes, right?
 * T here is specified as: i) function (i.e. lambda form or python function) T(k,z); ii) functions K(k), Z(z); iii) tabulated K(k), Z(z), right? Do we need iii, isn't it trivial for user to wrap in interp1d or something?
 * What about the cases where I have my own P(k). We had these in the past. I could in the present scheme just generate K(k) = P_mine(k)/P_dm(k), but looks really hackish -- couldn't you also give a function of P(k,z) in case you want to use something for youself. For example, a no-wiggle BAO? Of 2-halo contribution to the PS?  You could argue you don't need anything else then, but I object -- if nothing else for code readability sake it is better to have user specify T or K/Z in majority of cases. 
 * How does this interact with with the non-Limber code we have for large scales?

**Comment by damonge** [comment] 2019-04-21 19:50
Thanks @slosar 

>The derivative of Bessel function is a very good solution that puts RSD on the same footing. And we might eventually try to do some GR correction

Yes, exactly! I forgot to mention those.

> This is all for scalar functions, yes? Lensing here is E-modes, right?

Correct.

> T here is specified as: i) function (i.e. lambda form or python function) T(k,z); ii) functions K(k), Z(z); iii) tabulated K(k), Z(z), right? Do we need iii, isn't it trivial for user to wrap in interp1d or something?

All 3, and I'd add iv) tabulated T(k,z). I'd like to support the tabulated option, since, if the user knows that whatever sampling they have is sufficient, then we don't need to resample those functions (which we need to do to pass them into python) and they can save time.

> What about the cases where I have my own P(k)...

Yes, this will still be possible through the existing Pk2D class. Basically, to compute an angular power spectrum you'll need to pass two of the new tracers and a Pk2D (which will default to the halofit matter power spectrum if unspecified).

> How does this interact with with the non-Limber code we have for large scales?

Yes, good. Whatever non-Limber implementation we use will need to solve 
<a href="https://www.codecogs.com/eqnedit.php?latex=\dpi{100}&space;C^{uv}_\ell&space;=&space;\frac{2}{\pi}\,\int&space;d\chi&space;d\chi'&space;dk&space;k^2&space;P_{UV}(k,\chi,\chi')\,W_u(\chi)\,j_\ell(k\chi)\,W_v(\chi')\,j_\ell(k\chi')" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dpi{100}&space;C^{uv}_\ell&space;=&space;\frac{2}{\pi}\,\int&space;d\chi&space;d\chi'&space;dk&space;k^2&space;P_{UV}(k,\chi,\chi')\,W_u(\chi)\,j_\ell(k\chi)\,W_v(\chi')\,j_\ell(k\chi')" title="C^{uv}_\ell = \frac{2}{\pi}\,\int d\chi d\chi' dk k^2 P_{UV}(k,\chi,\chi')\,W_u(\chi)\,j_\ell(k\chi)\,W_v(\chi')\,j_\ell(k\chi')" /></a> (with derivatives of j_ell if needed). Currently Angpow doesn't do this in all generality, so we'll need to think about how to make it do so (or implement something else).

**Comment by slosar** [comment] 2019-04-22 19:44
It would be useful to ask authors of angpow how difficult would it be for them to do this.
There is also this https://arxiv.org/pdf/1705.05022, which I think should be straighforwardly generalizable to this setup.

**Comment by damonge** [comment] 2019-04-23 14:20
Good point @slosar , I'll ping them through the ongoing discussion in #584 
Yes, I'd like to have the FFTLog-based algorithm implemented in CCL

**Comment by jecampagne** [comment] 2019-04-25 13:12
H!
First let us remind the reformulation of the Cell integral according to Angpow current formula. Below the first line is just a C&P of the @slosar above equation, while the second is the formulation according to https://arxiv.org/pdf/1701.03592.pdf if one use the \chi formulation instead of the redshift one:
<a href="https://www.codecogs.com/eqnedit.php?latex=\begin{align}&space;C_\ell^{uv}&space;&=&space;\frac{2}{\pi}\int&space;d\chi&space;d\chi^\prime&space;W_u(\chi)W_v(\chi^\prime)&space;\int&space;dk\&space;k^2&space;P_{uv}(k,\chi,\chi^\prime)j_\ell(k&space;\chi)j_\ell(k&space;\chi^\prime)&space;\nonumber&space;\\&space;C_\ell^{uv}&space;&=&space;\frac{2}{\pi}\int&space;d\chi&space;d\chi^\prime&space;W_u(\chi)W_v(\chi^\prime)&space;\int&space;dk\&space;f_\ell(k,\chi)&space;f_\ell(k,\chi^\prime)&space;\nonumber&space;\end{align}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\begin{align}&space;C_\ell^{uv}&space;&=&space;\frac{2}{\pi}\int&space;d\chi&space;d\chi^\prime&space;W_u(\chi)W_v(\chi^\prime)&space;\int&space;dk\&space;k^2&space;P_{uv}(k,\chi,\chi^\prime)j_\ell(k&space;\chi)j_\ell(k&space;\chi^\prime)&space;\nonumber&space;\\&space;C_\ell^{uv}&space;&=&space;\frac{2}{\pi}\int&space;d\chi&space;d\chi^\prime&space;W_u(\chi)W_v(\chi^\prime)&space;\int&space;dk\&space;f_\ell(k,\chi)&space;f_\ell(k,\chi^\prime)&space;\nonumber&space;\end{align}" title="\begin{align} C_\ell^{uv} &= \frac{2}{\pi}\int d\chi d\chi^\prime W_u(\chi)W_v(\chi^\prime) \int dk\ k^2 P_{uv}(k,\chi,\chi^\prime)j_\ell(k \chi)j_\ell(k \chi^\prime) \nonumber \\ C_\ell^{uv} &= \frac{2}{\pi}\int d\chi d\chi^\prime W_u(\chi)W_v(\chi^\prime) \int dk\ f_\ell(k,\chi) f_\ell(k,\chi^\prime) \nonumber \end{align}" /></a>

In Angpow terminology the function f_\ell(k,\chi) (or f_\ell(k,z) ) is an "integrand" where \chi (or z) is fixed during the k-integration. Then the d\chi d\chi^\prime double integration is performed using a simple 2D-quadrature. So, there is a priori no problem to perform Angpow integration using the new schema. Note however that the  f_\ell(k,\chi) formulation may be more in the spirit of a generalized tracer function : it can include different bias functions, j_\ell higher order derivatives...

**Comment by damonge** [comment] 2019-04-25 15:20
@jecampagne OK, great,thanks! It seems the formalism is then applicable to angpow

**Comment by jecampagne** [comment] 2019-04-26 12:20
> @jecampagne OK, great,thanks! It seems the formalism is then applicable to angpow

Don't you think the "f_\ell(k,\chi)" more flexible? One not only can provide the different contributions as density, rsd, lensing..., but one also can 
consider different tracer, as well as galaxy species (ie. with different biais functions as in https://arxiv.org/pdf/1309.1321.pdf

**Comment by damonge** [comment] 2019-04-26 12:42
I'd rather not have to deal with 3D splines, since those will be complicated and slow to initialize. But we can definitely code things around angpow in a way that the different contributions are expressed as an f_ell(k,chi) transfer function, that's not a problem). 

The framework above is also able to incorporate the freedom you're referring to.

**Comment by jablazek** [comment] 2019-04-26 16:20
Structure looks good to me. It looks like the tracer definition will easily allow user defined P(k,z) by defaulting the transfer function to 1.

On the topic of B modes - this is an easy generalization (e.g. for IA)?

On the topic of non-limber: it looks like angpow may be well-suited for the general P(k,z) case. For cases where the k and z dependencies factorize, FFT methods should be faster. Xiao Fang has one in development that seems to work well (in python, and maybe eventually C). I think that Antonino Troja is implementing the Assassi method in C++.

**Comment by jecampagne** [comment] 2019-04-26 16:26
@jablazek how you decouple z (or chi) and k, as you have to deal with j_\ell(k r(z)) or j_\ell(k chi) and possibly its derivatives ?

**Comment by damonge** [comment] 2019-04-26 16:58
@jecampagne I believe @jablazek is referring to the prefactor multiplying the Bessel functions (what I've called "transfer functions" above)

@jablazek good to know that this is OK. I think it should be straightforward to include B-mode spectra in this formalism.

**Comment by jablazek** [comment] 2019-04-26 20:27
@jecampagne : maybe I've misunderstood your question, but I think the issue is how efficient it is to evaluate eq 3.5 of https://arxiv.org/pdf/1705.05022.pdf. If P(k,chi1,chi2) is simply P(k)F(chi1,chi2), then the c_n coefficients can be evaluated once with a single FFT, rather than requiring a new FFT at each step in the integrals over chi.

**Comment by jecampagne** [comment] 2019-04-27 09:49
@jablazek Ok I see your point thanks for the ref. In Angpow we also split the P(k,z) if it factorize in P(k)G(z) and put the G(z) with the W(z) function, but you're right we use 3C-algo for f_ell(k,z) = k Sqrt(P(k)) j_ell(kr(z)), but mind that now some people want to deal with b(k,z) bias functions...

**Comment by slosar** [comment] 2019-04-28 15:40
Ok, to recap this discussion: we're going with damonge's plan, but keep sufficient flexibility that one could call pluggable non-limber approximations if they are appropriate (based on factorizability, etc.)

**Comment by beckermr** [comment] 2019-07-29 17:16
this is done IIUIC, so closing.

**Closed by beckermr** 2019-07-29 17:16 UTC
Labels: !!SCIENCE!!, C/C++, Difficulty: Hard, Python
