### ISSUE TITLE
power spectrum segfault with cosmic emu

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#327] opened 2018-02-09 23:42 UTC
It's unclear where this is coming from, but CCL is crashing when sigmaR is called with the emulator. We need to understand where this is coming from by tracking it in C. Found by @alexander-mead.

**Comment by alexander-mead** [comment] 2018-02-10 03:13
I was just looking at this again. I seem to get kernel crashes in python whenever I set the 'transfer_function' to anything other than 'boltzmann', 'boltzmann_class' or 'class' and then ask for sigma(R). However, it seems to work okay if I set 'transfer_function='class' and matter_power_spectrum='emulator', so I think the problem is only when the 'transfer_function' is set to something funny. 

Come to think of it, I'm not quite sure how to interpret 'transfer_function='emulator''...

**Comment by philbull** [comment] 2018-02-13 18:15
@alexander-mead Does the behaviour change depending on whether you specify `A_s` or `sigma_8` when you initialise the `Cosmology` object?

Also, could you paste a minimal example that causes this problem, please?

**Comment by alexander-mead** [comment] 2018-02-13 18:54
The following python example exhibits this problem:

```
 import pyccl as ccl

cosmo = ccl.Cosmology(Omega_c=0.27, Omega_b=0.045, Omega_k=0., h=0.67, A_s=2.1e-9, n_s=0.96, transfer_function='emulator')

R=1.
print(ccl.sigmaR(cosmo,R))
```

**Comment by alexander-mead** [comment] 2018-02-13 19:01
And this persists if I replace '''As=2.1e-9''' with '''sigma8=0.8'''.

**Comment by alexander-mead** [comment] 2018-02-20 01:58
*UPDATE* this problem goes away is I fix both ```sigma8=0.8``` and ```N_nu_rel=3.04``` in the cosmology object. Therefore, I think it is a manifestation of the emulator not liking parameters outside its range, or something like that, rather than a problem with the sigmaR function. I also get crashes when asking for the power spectrum, nothing to do with the sigmaR function.

To be concrete, sigmaR and power functions work if:

```cosmo = ccl.Cosmology(Omega_c=0.27, Omega_b=0.05, Omega_k=0., h=0.67, sigma8=0.8, n_s=0.96, N_nu_rel=3.04,
                     transfer_function='emulator')```

but fail if

```cosmo = ccl.Cosmology(Omega_c=0.27, Omega_b=0.05, Omega_k=0., h=0.67, sigma8=0.8, n_s=0.96, N_nu_rel=3.04,
                     transfer_function='emulator')```

or

```cosmo = ccl.Cosmology(Omega_c=0.27, Omega_b=0.05, Omega_k=0., h=0.67, A_s=2.1e-9, n_s=0.96, N_nu_rel=3.046,
                     transfer_function='emulator')```

**Comment by alexander-mead** [comment] 2018-02-20 02:06
I changed the name of this issue to reflect the fact that it has nothing to do with the sigmaR function. It may be related to other issues that are already open and that people are aware of.

**Comment by elisachisari** [comment] 2018-03-07 16:08
@alexander-mead When using the cosmic emulator, N_nu_rel has to be fixed to 3.04. This is because of how the emulator was calibrated. So CCL enforces this choice. If you call CCL with the emulator but use anything other than N_nu_rel =3.04, it will quit. Within the C files, this happens in ccl_power.c when you try to compute the matter power spectrum. This explains why your third cosmology seg faults. Cosmologies 1 and 2 seem to be he same and both work for me. @philbull: the error message raised by the emulator when N_nu_rel !=3.04 is not being passed around to python, is there a way to fix this?

**Comment by elisachisari** [comment] 2018-03-21 15:16
Pinging @philbull about this

**Comment by philbull** [comment] 2018-07-11 16:22
@elisachisari @alexander-mead I think this issue is fixed now. There have been a few improvements in error handling and catching incompatible combinations of cosmological parameters over the last few months. I ran a couple of Alex's examples, and they do now seem to raise Python errors, as they should.

**Closed** 2018-07-11 18:16 UTC
Labels: BUG
