### ISSUE TITLE
Angpow C(l) at a given l depends on l_max

### ISSUE THREAD

**Issue by NiallMac** [LSSTDESC/CCL#495] opened 2018-10-12 15:37 UTC
Hi there, I've been looking at the ccl C_l predictions for the DES Y1 redmagic n(z)s. I was trying to compare the angpow and Limber clustering predictions, but then noticed some significant sensitivity (up to a few percent) in the angpow prediction to the l_max used, which made that comparison tricky. The plot attached shows the fractional difference in the the angpow C_l prediction for exactly the same l values (0<l<300), but in one case the calculation was done with l_max=600 (see the `angpow_lmax_test` function in the [script](https://gist.github.com/NiallMac/b48ea86ba759d61d1956c662950c0ad4) used to generate the plot). 

I am guessing this is either coming from
i) me screwing up/misunderstanding the usage, apologies if that is the case.
ii) l_max is used to set some accuracy settings, which changes the result at a given l.

I've also attached the n(z)s ([rm_y1_nz.txt](https://github.com/LSSTDESC/CCL/files/2473680/rm_y1_nz.txt)) in case anyone wants to run this script. 
![angpow_cl_test](https://user-images.githubusercontent.com/7635269/46878795-2a58dc80-ce12-11e8-841c-8011bf8ae6ab.png)

**Comment by jeremyneveu** [comment] 2018-10-12 18:17
Hi @NiallMac. The setting of l_max for angpow set the value for k_max in the P(k) integral with the relation k_max = \pi * l_max / chi_min, where chi_min is the comoving distance of the closest edge of the closest bin. Then depending on the bin distance, the l_max should be set appropriately. I see that your first bin starts at z=0.1, then you should wonder if the corresponding k_max makes sense considering your data. My recipe would be to start with a high l_max, decrease it and see where it starts diverging beyond your requirements, at least for the first bin (the blue curve which is the worst).

BTW this is the first time I hear Angpow is used for science, if you need help for the parameter tuning please don't hesitate to ask.

**Comment by NiallMac** [comment] 2018-10-12 18:46
Hi @jeremyneveu . So then using a higher l_max should increase the accuracy at all ell? That is not what I'm seeing...

For example here is the comparison I mentioned to the Limber calculation for l_max=300 and l_max=600. The agreement at high l for l_max=600 is quite a bit worse.
![ccl_redmagic_lmax300](https://user-images.githubusercontent.com/7635269/46888092-7feeb280-ce2d-11e8-96f6-d6af7c148c79.png)
![ccl_redmagic_lmax600](https://user-images.githubusercontent.com/7635269/46888097-83823980-ce2d-11e8-8e8d-9a2a89e22e01.png)

**Comment by NiallMac** [comment] 2018-10-12 18:47
> BTW this is the first time I hear Angpow is used for science, if you need help for the parameter tuning please don't hesitate to ask.
P.S. Thanks! :)

**Comment by jeremyneveu** [comment] 2018-10-15 15:13
Ok thank for the plots. Using a higher l_max may not increase the accurcay of the integrals if the integrand does not decrease rapidly enough. Also as l_max and k_max are linked, numerically you will see this l_max dependence problem using other methods. I think then that what should drive the choice of the l_max is your data. In particular for the first shell, k_max should be very high. For z_min=0.1, chi_min=436 Mpc then k_max = 2.16 Mpc^-1 for l_max = 300. Is this k_max pertinent concerning the non-linearities of the P(k) or even the bining of your data in this bin ? Then you can take the reverse problem and regarding the k_max relevant for your case set the l_max.

**Comment by NiallMac** [comment] 2018-10-15 16:04
That k_max is reasonable for my application, yes. I think I understand your point that the integrand may not converge rapidly enough for a given k_max. But in that case shouldn't the result at a given l get more accurate as I increase l_max, since that correspondingly increases k_max? But here the opposite happens, so I guess I'm not understanding your suggestion.

**Comment by jecampagne** [comment] 2018-10-16 07:43
Hi, this is the same problem with the Class Lmax/cl_kmax. You certainly guess that there is need of P(k) regularisation above a k_max if you want to get the linear P(k) working.

**Comment by NiallMac** [comment] 2018-10-16 13:08
Thanks @jecampagne, what is your suggestion exactly? To apply some filter to P(k) - if so how would this be chosen?

**Comment by NiallMac** [comment] 2018-10-18 13:41
Thanks Jean-Eric. Is there some set of accuracy settings in angpow that I would need to increase to get an arbitrarily (numerically) accurate prediction? I'd like to know this so I have something to do convergence testing against.

**Comment by jecampagne** [comment] 2018-10-19 07:37
@NiallMac The main problem is that the angpow version in CCL is the very first one that we have used for the paper. Afterwards I have made several changes that are not yet included in Angow via CCL as we do not want to make troubles in the CCL paper review. So, the original quadrature to perform z-integrations in the CCL/angpow version is not the optimal one but it may suffice. As an advise do not use the "cuts"  (Weights and Radial) as this was a  "no-good idea" and sorry for this (in the new release these has been removed), so in practice one   
  total_weight_cut = 0   (the default is may be 10^-6)
  has_deltaR_cut = 0   (this is certainly the default)
JE

**Comment by NiallMac** [comment] 2018-10-19 13:54
Thanks @jecampagne. It seems to me pretty essential to have a version of angpow in ccl that works reasonably for common applications such as this, regardless of troubles for the CCL paper review, or it shouldn't be included at all. How easy would it be to update to the optimal one?

**Comment by jeremyneveu** [comment] 2018-10-19 17:40
Hi @NiallMac. The Angpow in CCL was benchmarked on CLASS and on the other non-limber computation provided bu CCL (method=native). In PR#283 you can see that for close redshift bins even for l_max = 200 the mean relative difference between the two methods with respect to the cosmic variance is below 2 order of magnitudes : https://github.com/LSSTDESC/CCL/pull/283 So Angpow is working as we would expect in these cases. You can try to set the two parameters proposed by @jecampagne going into the CCL/build/Angow directory and change the default parameter values in angpow_parameters.cc. I have just tried and did not see differences using your plot script, maybe try you also (I am currently travelling, not easy to work).   
The inclusion of the last version of Angpow is not hard I believe, for the coding part at least, but the rebenchmarking operation can be long.

**Comment by NiallMac** [comment] 2018-10-19 17:57
Thanks @jeremyneveu , those are useful plots. Just to make sure I understand the colorscale, do you mind describing for me exactly the quantity you calculate for that?

**Comment by NiallMac** [comment] 2018-10-22 17:02
@jeremyneveu I'm afraid that's still not completely clear to me - what exactly is "cosmic variance" in your equation? Do you take the mean of the ratio, or do you take the mean of the numerator, with the denominator representing the error on that mean? Would your formula account for the possibility of all the C_ells being different by a small amount compared to the cosmic variance on any single C_l, but coherently so that the net effect is significant (e.g. if 100 ells are offset in the same direction by 0.1sigma)?

**Comment by jeremyneveu** [comment] 2018-10-24 07:49
@NiallMac I have to correct my formula, I used : 
< abs( (C_ell^Angpow - C_ell^CCL_native_non_Limber)/C_ell^CCL_native_non_Limber )/ cosmic variance >_ell
with cosmic variance = sqrt(2/(2l+1))
In other words, I checked that the relative difference between the two codes is below by at least an order of magnitude (two orders in general) with respect to the cosmic variance. The things I would like to point is that the ell_max variation you showed with Angpow will appear also with the other algorithm, because intrinsically chosing ell_max is chosing k_max.
To answer the second part of your question, yes the relative difference between the 2 algorithms is smooth with ell with in general a small shift at many ells.

**Comment by NiallMac** [comment] 2018-10-24 14:14
@jeremyneveu ok that seems problematic for a benchmark test - in an analysis we combine information from a wide range of ell, so any inaccuracies that are coherent across a range of ell are additive, while the noise is beaten down by combining many ell modes. Comparing the inaccuracies ell-by-ell to the cosmic variance does not capture this at all.

**Comment by jeremyneveu** [comment] 2018-10-26 09:44
@NiallMac This algorithm comparaison points out a systematic error between the two implementations of the non-Limber C_ell in CCL. Indeed this is "coherent across a range of ell" but we showed that this is well below the minimum statistical error you expect from a data analysis, e.g. the cosmic variance.

**Comment by NiallMac** [comment] 2018-10-26 16:29
A more suitable formula would be:
< (C_ell^Angpow - C_ell^CCL_native_non_Limber) >_ell / \sqrt( \Sum_ell V(elll) / N_ell )
Where V(ell) is the cosmic variance for C(ell), and N_ell is the total number of ells. Now the denominator is actually the error on the mean taken in the numerator. 

Probably an even better option would be to inverse variance weight the mean.

**Comment by elisachisari** [comment] 2018-11-02 17:37
@NiallMac Looking over this thread, I agree the current error bars might not be sufficient for LSST. The goal for the paper was to present CCL and a method for numerical validation, but we expect that eventually we will have forecasts to determine whether the numerical precision achieved is good enough (i.e., doesn't induce any bias in the cosmological parameters). For this, we need a proper forecasting pipeline which is not yet in place, but it should be the next step. There will also be a trade-off between speed and accuracy that we will need to explore. For your particular application, though, indeed you could do as you say, explore the l_max value (or any other precision parameters in CCL) that allow you to reach the criterion you established above.

**Comment by NiallMac** [comment] 2018-11-02 18:58
As described above, it doesn't seem to be the case that accuracy increases with l_max, and it's not clear that any of the parameters the ccl user has access to will help either. I completely understand if LSST precision is beyond requirements right now, but we're talking about percent-level effects here, which is some way from LSST precision presumably, and it would be good to provide some useful quantification of the accuracy of the current implementation to users.

**Comment by elisachisari** [comment] 2018-11-02 20:16
We can certainly explore this further. I would say perhaps first extending our checks in the case of angpow vs. the native nonlimber implementation (have you looked at that comparison?), and then reproducing the test you did for the limber case. This should probe a realistic range of redshifts and ell values. It shouldn't be hard to set that up within CCL itself. Beyond l_max, I can imagine other parameters playing a role as well. Let's add this to the to-do list.

**Comment by c-d-leonard** [comment] 2020-03-20 13:25
I think this issue may be obsolete due to the fact that we no longer support angpow currently. @elisachisari?

**Comment by damonge** [comment] 2022-06-15 10:27
I agree. Closing

**Closed by damonge** 2022-06-15 10:27 UTC
Labels: Difficulty: Easy, new-contributor-friendly, Checks
