### ISSUE TITLE
How to set spline/accuracy parameters - failing

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#1021] opened 2023-02-07 09:39 UTC
If I try to change the CCL accuracy parameters according to this recipe:

https://ccl.readthedocs.io/en/v2.0.0/source/notation_and_other_cosmological_conventions.html?highlight=parameters#cosmological-parameters

I get a warning that this will be deprecated in the next version:
`
CCLDeprecationWarning: Direct assignment of gsl_params is deprecated and an error will be raised in the next CCL release. Set via pyccl.gsl_params.K_MAX_SPLINE before instantiation.`

So I tried the way that is suggested in the warning. But this fails with the following error:

`KeyError: Parameter K_MAX_SPLINE does not exist.`

So we need to: (1) fix this before the next version and (2) make sure to update the docs.

**Comment by damonge** [comment] 2023-02-07 10:20
Can you check if this should instead be `ccl.spline_params.K_MAX_SPLINE`? If so, I can fix the error message quickly.

**Comment by nikfilippas** [comment] 2023-02-07 11:15
The spline parameters now live in `pyccl.spline_params`. When I try it the old way, it correctly points me to the new way of changing the parameters:
```
>>> cosmo = ccl.CosmologyVanillaLCDM()
>>> cosmo.cosmo.spline_params.K_MAX_SPLINE = 100
CCLDeprecationWarning: Direct assignment of spline_params is deprecated and an error will be raised in the next CCL release. Set via `pyccl.spline_params.K_MAX_SPLINE` before instantiation.
>>> ccl.spline_params.K_MAX_SPLINE = 30
```
The docs do need updating however. This is similar to #1007 .
But unless I misunderstood the issue, I don't think this is a bug.

**Comment by damonge** [comment] 2023-02-07 11:16
The error message is wrong, right?

**Comment by nikfilippas** [comment] 2023-02-07 11:17
Why is it wrong?

**Comment by damonge** [comment] 2023-02-07 12:41
Elisa's warning message read `Set via pyccl.gsl_params.K_MAX_SPLINE before instantiation`. Is that an old version?

**Comment by nikfilippas** [comment] 2023-02-07 12:43
I think so, I have the latest version and it shows ok. Can you try with yours?

**Comment by nikfilippas** [comment] 2023-04-04 19:11
I can't reproduce this - is this still an issue? If not we can close it.

**Comment by nikfilippas** [comment] 2023-04-20 07:46
Closing this in prep for v3 as couldn't repro, but feel free to reopen if still an issue.

**Closed by nikfilippas** 2023-04-20 07:46 UTC
Labels: BUG, API
