### ISSUE TITLE
The central installation of CCL on NERSC doesn't work

### ISSUE THREAD

**Issue by cosmicshear** [LSSTDESC/CCL#307] opened 2018-01-09 13:04 UTC
After running

> source /global/common/cori/contrib/lsst/ccl/setupPyCCL.sh

I try to compile ./tests/ccl_sample_run.c by doing 
```
(CCL) user@cori07:~/CCL> gcc -Wall -Wpedantic -g -I$CCL_NERSC_DIR/$CCL_NERSC_VER/include $CPPFLAGS -std=gnu99 -fPIC tests/ccl_sample_run.c -o tests/ccl_sample_run -L$CCL_NERSC_DIR/$CCL_NERSC_VER/lib $LDFLAGS -lgsl -lgslcblas -lm -lccl
In file included from /global/common/cori/contrib/lsst/ccl/0.2/include/ccl.h:22:0,
                 from tests/ccl_sample_run.c:4:
/global/common/cori/contrib/lsst/ccl/0.2/include/ccl_core.h:4:28: fatal error: gsl/gsl_spline.h: No such file or directory
 #include "gsl/gsl_spline.h"
                            ^
compilation terminated.
```

but it has some problems with gsl.

**Comment by elisachisari** [comment] 2018-01-09 14:14
@cosmicshear. Have you followed these instructions?
https://github.com/LSSTDESC/CCL/wiki/Using-and-Installing-CCL-on-NERSC

**Comment by cosmicshear** [comment] 2018-01-09 14:29
@elisachisari yes, I did.

**Comment by elisachisari** [comment] 2018-01-09 14:32
@heather999 @WeikangLin: have you encountered this problem before?

**Comment by WeikangLin** [comment] 2018-01-09 15:35
@cosmicshear @elisachisari @heather999 I think Cori and Edison at NERSC are under maintenance today (Jan 9th, 06:00-22:00), which is why I had problems of logging in. I will look into this later.

**Comment by tmcclintock** [comment] 2018-01-09 17:38
NERSC is down until 10 PM PST [link](http://www.nersc.gov/live-status/motd/). @cosmicshear try this again tomorrow and close this if there is no more issue at that time. Thanks!

**Comment by cosmicshear** [comment] 2018-01-10 07:52
I got different warnings and errors this time.

```
tests/ccl_sample_run.c: In function 'main':
tests/ccl_sample_run.c:51:104: warning: passing argument 13 of 'ccl_parameters_create' makes pointer from integer without a cast [-Wint-conversion]
   ccl_parameters params = ccl_parameters_create(OC, OB, OK, NREL, NMAS, MNU, W0, WA, HH, NORMPS, NS,-1,-1,-1,-1,NULL,NULL, &status);
                                                                                                        ^
In file included from /global/common/cori/contrib/lsst/ccl/0.2/include/ccl.h:22:0,
                 from tests/ccl_sample_run.c:4:
/global/common/cori/contrib/lsst/ccl/0.2/include/ccl_core.h:173:16: note: expected 'double *' but argument is of type 'int'
 ccl_parameters ccl_parameters_create(double Omega_c, double Omega_b, double Omega_k, double N_nu_rel, double N_nu_mass, double mnu, double w0, double wa, double h, double norm_pk, double n_s,int nz_mgrowth,double *zarr_mgrowth,double *dfarr_mgrowth, int *status);
                ^~~~~~~~~~~~~~~~~~~~~
tests/ccl_sample_run.c:51:107: warning: passing argument 14 of 'ccl_parameters_create' makes pointer from integer without a cast [-Wint-conversion]
   ccl_parameters params = ccl_parameters_create(OC, OB, OK, NREL, NMAS, MNU, W0, WA, HH, NORMPS, NS,-1,-1,-1,-1,NULL,NULL, &status);
                                                                                                           ^
In file included from /global/common/cori/contrib/lsst/ccl/0.2/include/ccl.h:22:0,
                 from tests/ccl_sample_run.c:4:
/global/common/cori/contrib/lsst/ccl/0.2/include/ccl_core.h:173:16: note: expected 'double *' but argument is of type 'int'
 ccl_parameters ccl_parameters_create(double Omega_c, double Omega_b, double Omega_k, double N_nu_rel, double N_nu_mass, double mnu, double w0, double wa, double h, double norm_pk, double n_s,int nz_mgrowth,double *zarr_mgrowth,double *dfarr_mgrowth, int *status);
                ^~~~~~~~~~~~~~~~~~~~~
tests/ccl_sample_run.c:51:110: warning: passing argument 15 of 'ccl_parameters_create' makes pointer from integer without a cast [-Wint-conversion]
   ccl_parameters params = ccl_parameters_create(OC, OB, OK, NREL, NMAS, MNU, W0, WA, HH, NORMPS, NS,-1,-1,-1,-1,NULL,NULL, &status);
                                                                                                              ^
In file included from /global/common/cori/contrib/lsst/ccl/0.2/include/ccl.h:22:0,
                 from tests/ccl_sample_run.c:4:
/global/common/cori/contrib/lsst/ccl/0.2/include/ccl_core.h:173:16: note: expected 'int *' but argument is of type 'int'
 ccl_parameters ccl_parameters_create(double Omega_c, double Omega_b, double Omega_k, double N_nu_rel, double N_nu_mass, double mnu, double w0, double wa, double h, double norm_pk, double n_s,int nz_mgrowth,double *zarr_mgrowth,double *dfarr_mgrowth, int *status);
                ^~~~~~~~~~~~~~~~~~~~~
tests/ccl_sample_run.c:51:27: error: too many arguments to function 'ccl_parameters_create'
   ccl_parameters params = ccl_parameters_create(OC, OB, OK, NREL, NMAS, MNU, W0, WA, HH, NORMPS, NS,-1,-1,-1,-1,NULL,NULL, &status);
                           ^~~~~~~~~~~~~~~~~~~~~
In file included from /global/common/cori/contrib/lsst/ccl/0.2/include/ccl.h:22:0,
                 from tests/ccl_sample_run.c:4:
/global/common/cori/contrib/lsst/ccl/0.2/include/ccl_core.h:173:16: note: declared here
 ccl_parameters ccl_parameters_create(double Omega_c, double Omega_b, double Omega_k, double N_nu_rel, double N_nu_mass, double mnu, double w0, double wa, double h, double norm_pk, double n_s,int nz_mgrowth,double *zarr_mgrowth,double *dfarr_mgrowth, int *status);
                ^~~~~~~~~~~~~~~~~~~~~
tests/ccl_sample_run.c:105:23: warning: implicit declaration of function 'ccl_cl_tracer_cmblens_new'; did you mean 'ccl_cl_tracer_lensing_new'? [-Wimplicit-function-declaration]
   CCL_ClTracer *ct_cl=ccl_cl_tracer_cmblens_new(cosmo,1100.,&status);
                       ^~~~~~~~~~~~~~~~~~~~~~~~~
                       ccl_cl_tracer_lensing_new
tests/ccl_sample_run.c:105:23: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
tests/ccl_sample_run.c:164:22: warning: implicit declaration of function 'ccl_specs_create_gaussian_photoz_info'; did you mean 'ccl_specs_create_photoz_info'? [-Wimplicit-function-declaration]
   pz_info_gaussian = ccl_specs_create_gaussian_photoz_info(sigma_z0);
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                      ccl_specs_create_photoz_info
tests/ccl_sample_run.c:164:20: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   pz_info_gaussian = ccl_specs_create_gaussian_photoz_info(sigma_z0);
                    ^
tests/ccl_sample_run.c:163:17: warning: variable 'pz_info_gaussian' set but not used [-Wunused-but-set-variable]
   user_pz_info *pz_info_gaussian;
                 ^~~~~~~~~~~~~~~~
```

**Comment by WeikangLin** [comment] 2018-01-10 15:43
@cosmicshear It it probably a problem of version. The central installed CCL at NERSC is of version 0.2. If you are using the latest CCL from the repository, you will get the above warning because the parameter and model initiations have been changed. You may copy CCL_0.2 from 
`/global/common/cori/contrib/lsst/ccl/downloads/0.2.tar.gz` ,
and compile tests/ccl_sample_run.c. Alternatively, you can install the latest CCL on NERSC locally. Instructions are provided on the wiki page.

@tmcclintock @elisachisari @heather999 Do you know if there is any plan for the update of CCL at NERSC? At the moment, I will put a note on the wiki page saying that users can download version 0.2 from the above path.

**Comment by elisachisari** [comment] 2018-01-10 15:47
thanks @WeikangLin. What if we update the CCL version in NERSC to the paper version once available? That will be our next CCL release.

**Comment by WeikangLin** [comment] 2018-01-10 17:19
@elisachisari That sounds good. But most likely similar warnings will still show up sooner or later if an internal developer compiles and runs the latest ccl_sample_run.c from the repository. Maybe one way out is to always put a package of the installed CCL along with the library at NERSC, which is the case for the current version. 

@tmcclintock @elisachisari @heather999 When installing the latest version at NERSC, I come across a warning `configure: error: Couldn't find libclass.` It doesn't show up if I install version 0.2 instead. And I don't have this warning when I install the latest version on my Mac. Any ideas about this?

**Comment by fjaviersanchez** [comment] 2018-01-10 17:25
@WeikangLin It seems that it is not finding CLASS. Maybe it is not installed or it's not finding it. To install it you can execute the python script `class_install.py` in the CCL root directory.

**Comment by WeikangLin** [comment] 2018-01-10 17:52
Thanks @fjaviersanchez. After I install class, configure goes through. But new warning shows up when I do make, which doesn't show up with v0.2:
```
/usr/bin/ld: /usr/lib64/libmvec_nonshared.a(svml_finite_alias.oS): relocation R_X86_64_PC32 against undefined symbol `_ZGVbN2v_log@@GLIBC_2.22' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Makefile:571: recipe for target 'libccl.la' failed
make[2]: *** [libccl.la] Error 1
make[2]: Leaving directory '/global/u2/w/weikang/CCL'
Makefile:999: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/global/u2/w/weikang/CCL'
Makefile:452: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by fjaviersanchez** [comment] 2018-01-10 20:24
It looks like you have to add a flag before compiling CLASS. You can maybe export CFLAGS="-fPIC -dynamic" before running the `class_install.py` script? Hopefully that works.

**Comment by WeikangLin** [comment] 2018-01-10 21:53
@fjaviersanchez It still has the above warning, and some new problems show up:
```
cc1: warning: unrecognized gcc debugging option: y
cc1: warning: unrecognized gcc debugging option: n
cc1: warning: unrecognized gcc debugging option: m
cc1: warning: unrecognized gcc debugging option: i
cc1: warning: unrecognized gcc debugging option: c
```

**Comment by fjaviersanchez** [comment] 2018-01-10 22:22
@WeikangLin I'll try to reproduce the problem and get back to you if I manage to solve it.

**Comment by WeikangLin** [comment] 2018-01-10 22:26
@fjaviersanchez I redid everything, and it seems that adding CFLAGS="-fPIC -dynamic" before I install class and before I load the necessary modules can have CCL installed and ccl_sample_run.c compiled.
The only problem I have is the warnings:
```
cc1: warning: unrecognized gcc debugging option: y
cc1: warning: unrecognized gcc debugging option: n
cc1: warning: unrecognized gcc debugging option: m
cc1: warning: unrecognized gcc debugging option: i
cc1: warning: unrecognized gcc debugging option: c
```

**Comment by fjaviersanchez** [comment] 2018-01-10 22:27
ohhh I see it's because the option is `--dynamic` sorry about that!

**Comment by WeikangLin** [comment] 2018-01-10 22:45
@fjaviersanchez If I uses the option --dynamics, errors show up at configure: 
`configure: error: C compiler cannot create executables`. I will continue to look into it later.

**Comment by fjaviersanchez** [comment] 2018-01-10 23:42
@WeikangLin apologies for the confusing directions. I think you can just forget about the `--dynamic` flag for now. I think it is not necessary, I was mistakingly associating this error to something else. Sorry again. (Just use the `export CFLAGS=-fPIC` and that should be enough hopefully)

**Comment by WeikangLin** [comment] 2018-01-11 04:12
@fjaviersanchez Yes, it works well now. Thank you very much for your help. @cosmicshear I have updated the instructions for installation on the wiki page. If you want to install your own latest version of CCL on NERSC, those steps should work (hopefully).

**Comment by elisachisari** [comment] 2018-02-12 16:41
@WeikangLin can we close this?

**Comment by WeikangLin** [comment] 2018-02-12 16:45
@elisachisari Yes.

**Closed** 2018-02-12 16:46 UTC
Labels: C/C++, Installation, Testing
