### ISSUE TITLE
WARNING: ccl_cls.c: ccl_angular_cl_native(): GSL error: generic failure

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/CCL#397] opened 2018-06-22 20:50 UTC
When try to call pyccl.angular_cl using the attached code and a fairly vanilla n(z) on my laptop we get repeated printouts of this error message:

```
WARNING: ccl_cls.c: ccl_angular_cl_native(): GSL error: generic failure
```
followed by 
```
Traceback (most recent call last):
  File "ccl_error_thing.py", line 23, in <module>
    clarr=ccl.angular_cl(cosmo, tracer, tracer, larr)
  File "/usr/local/lib/python3.6/site-packages/pyccl/cls.py", line 409, in angular_cl
    check(status)
  File "/usr/local/lib/python3.6/site-packages/pyccl/pyutils.py", line 24, in check
    raise RuntimeError("Error %s: %s" % (pyccl.core.error_types[status], msg))
RuntimeError: Error CCL_ERROR_INTEG: 
```
[nz.txt](https://github.com/LSSTDESC/CCL/files/2129101/nz.txt)
[ccl_error_thing.py.txt](https://github.com/LSSTDESC/CCL/files/2129104/ccl_error_thing.py.txt)

**Comment by tilmantroester** [comment] 2018-06-25 11:28
I just tried your example on the latest master and can't reproduce the error. I don't get any warning messages, even with `debug_mode(True)` enabled.

**Comment by tilmantroester** [comment] 2018-06-28 10:52
OK, I can reproduce the error when I install CCL with pip but not on the current master. 
@EiffL what commit is the pypi version based on?

**Comment by EiffL** [comment] 2018-06-28 22:32
@tilmantroester the pip releases are tagged in the release section, the latest tag is https://github.com/LSSTDESC/CCL/releases/tag/v0.3.1
(I had to manually bump the pypi version to 0.3.2, but it's based on the same tag, adnd shouldn't happen in the future, now that it is automated)

**Comment by cwwalter** [comment] 2018-06-29 04:33
I just scrolled back and looked at what I was doing yesterday and it was already installing 0.3.2:

```
wasabi:~ % pip install pyccl
Collecting pyccl
  Downloading https://files.pythonhosted.org/packages/11/8a/da1b543122bbd0579c90bad325cd1a2532e0b90c2034d8337c3af378d5f7/pyccl-0.3.2.tar.gz (470kB)
    100% |████████████████████████████████| 471kB 2.2MB/s 
```

So I suspect this problem is still in 0.3.2.  Or did I misunderstand your comment?

**Comment by EiffL** [comment] 2018-06-29 04:47
Yes, sorry if I wasn't very clear, I meant v0.3.1 and v0.3.2 are the same, the bump in version was just to satisfy PyPi. And master has evolved quite a bit since then I suspect. If the problem is solved using master, then we could just cut a new update v0.3.3 at some point

**Comment by EiffL** [comment] 2018-06-29 04:59
hum..... that's really weird. @cwwalter @joezuntz I can't reproduce your problems on my machine, I'm exactly running your scripts but I don't get any messages, whether I use v0.3.2 or master :-/

**Comment by cwwalter** [comment] 2018-06-29 05:02
Did you install it via pip? Or some other way?

**Comment by EiffL** [comment] 2018-06-29 05:04
I install from source, by cloning the repo and running `python setup.py build` or `python setup.py install --user`. You get a lot more compilation messages that way.

If I had to guess, I would say the culprit may be the version of GSL that you guys are using. If found during the install process, CCL will use whatever GSL is on your machine, otherwise it will download and build v2.4 I think. I have 2.5 on my computer

**Comment by cwwalter** [comment] 2018-06-29 05:07
Hmm... but tilmantroester said above:

> OK, I can reproduce the error when I install CCL with pip but not on the current master.
@EiffL what commit is the pypi version based on?

I can actually report that I  installed the conda version of GSL yesterday as a test and and it made no difference (but it is also 2.4).

**Comment by EiffL** [comment] 2018-06-29 05:10
ah, yes, good point. I assumed I would be able to reproduce the problem by checking out the version of the code corresponding to the PyPi release, but there might be a less obvious problem during the pip install. I'll check what happens on my machine

**Comment by EiffL** [comment] 2018-06-29 05:22
Ok, my bad, confirmed. v0.3.2 reproduces that issue when installed from PyPi. I'm looking into it

**Comment by cwwalter** [comment] 2018-06-29 05:33
BTW: While you are checking I also noticed this when I checked a random notebook:

```
import numpy as np
import pylab as plt
import pyccl as ccl
%matplotlib inline

cosmo = ccl.Cosmology(Omega_c=0.27, Omega_b=0.045, h=0.67, A_s=2.1e-9, n_s=0.96)

z = np.linspace(0., 3., 200)
i_lim = 26. # Limiting i-band magnitude
z0 = 0.0417*i_lim - 0.744

Ngal = 46. * 100.31 * (i_lim - 25.) # Normalisation, galaxies/arcmin^2
pz = 1./(2.*z0) * (z / z0)**2. * np.exp(-z/z0) # Redshift distribution, p(z)
dNdz = Ngal * pz # Number density distribution

lens1 = ccl.ClTracerLensing(cosmo, False, z=z, n=dNdz)
lens2 = ccl.ClTracerLensing(cosmo, False, n=(z, dNdz))

bias_ia = np.ones(z.size) # Intrinsic alignment bias factor
f_red = 0.5 * np.ones(z.size) # Fraction of red galaxies
lens1_ia = ccl.ClTracerLensing(cosmo, True, z=z, n=dNdz, bias_ia=bias_ia, f_red=f_red)

z_ia = np.linspace(0., 3., 5) # Only 5 redshift bins
bias_ia2 = np.ones(z_ia.size)
lens2_ia = ccl.ClTracerLensing(cosmo, True, n=(z, dNdz), bias_ia=(z_ia, bias_ia), f_red=(z, f_red))
```

gives:

```
wasabi:~ % Assertion failed: (nz_ba == nba), function cl_tracer_new_wrapper, file /private/var/folders/4t/66c5hggs5_1f191_9f2dljh80000gn/T/pip-build-mlpyir1_/pyccl/build/pyccl/cclPYTHON_wrap.c, line 4184.
kernel 61f5b829-1e50-4076-afaa-15f15d05b03f restarted
```

Do you see that in addition?

**Comment by EiffL** [comment] 2018-06-29 05:45
Argh, that's quite bad... That notebook was supposed to trigger another error, for which we have a pending PR https://github.com/LSSTDESC/CCL/pull/353  I haven't seen that one before, we may have to open another issue... Thanks for finding this!

Regarding the present issue, I'm very confused, the source in the tarball used by pip is identical to master (for the .py and .c files) I don't understand where that error is coming from. I'll do more digging in the morning.

**Comment by tilmantroester** [comment] 2018-06-29 11:00
I had a quick look at the GSL code and the "generic failure" error is used quite rarely. The relevant line in the QAG routine is http://git.savannah.gnu.org/cgit/gsl.git/tree/integration/qag.c?h=release-2-5#n261, I think. I actually don't understand how one can even trigger that, since the exit conditions for the preceding `while` loop all seem to be covered by the other `if` statements.

**Comment by EiffL** [comment] 2018-07-16 18:32
Ok, I think we found the source of this problem, and it had to do with missing CLASS files, which triggered a chain of errors which got caught by the GSL warning mechanism instead of being transmitted as a CLASS error.
We now should have fixed the CLASS issue, so this error should not happen in master anymore, however the GSL warning triggered by a CLASS error issue is not solved, so we should open a separate issue for this.

**Comment by elisachisari** [comment] 2018-07-16 23:08
I've approved @EiffL's PR and have seen this issue go away, so I'll close it and open the other one instead.

**Closed by elisachisari** 2018-07-16 23:08 UTC
