### ISSUE TITLE
Latest version of CCL slow in angular_cl()

### ISSUE THREAD

**Issue by xinucode** [LSSTDESC/CCL#641] opened 2019-06-25 17:49 UTC
After using the ccl library in the LSSLike/hsc_fit MCMC sampling
program, we noticed that the latest version of CCL is an order of magnitude slower
compared to the `lss_hsc_work` branch.

Attached is a short script that outputs the calculation time of angular_cl() in a typical use case.

Outputs in different branches are:

Pyccl version:  0.10.dev200+g5aa10d1 (`lss_hsc_work`)
Time of computation:  2.6551663875579834

Pyccl version:  1.0.1.dev146+gef8008d.d20190624 (`master`)
Time of computation:  27.00929045677185

Code is here:
[cclCompTimer.zip](https://github.com/LSSTDESC/CCL/files/3326002/cclCompTimer.zip)

**Comment by damonge** [comment] 2019-06-25 17:56
Before anyone freaks out, I'm pretty sure this is due to the fact that the previous version computed C_ells only at specific values of ell and then interpolated, whereas the new version computes them at every ell requested.

I think the current implementation in the HSC project computes the power spectra at all integer ells (see https://github.com/LSSTDESC/LSSLike/blob/42b71c614b7df0f0b3e9097e1546996d2c7fbc17/hsc/hsc_core_module.py#L92), which would explain why it's so slow.

So the short-term solution if you want to use the master branch is to avoid computing C_ells at all ells, and choose only a few and then interpolate.

And before anyone complains: the reason why CCL doesn't interpolate anymore is that we thought this was creating too much code overhead because of this, and that we should let users do that on their end (there's a long discussion about this in one of the issues between me and @beckermr ). Tagging @slosar too.

**Comment by beckermr** [comment] 2019-06-25 18:02
Yes, this is the reason. I'd roll a quick interpolation locally with something like scipy.

**Comment by slosar** [comment] 2019-06-25 22:41
I'm not sure what exactly is @beckermr becerkm suggesting. Ideally I would like to have an option for CCL to do interpolation that is transparent for the user if the number of points is large enough and option to force every ell evaluation. I think interpolation is common enough use case that it is wastefull if every user needs to do it (and more importantly think about ell spacing, et.c)

**Comment by damonge** [comment] 2019-06-25 23:46
@slosar I tend to agree with this, but this exact conversation already happened here: https://github.com/LSSTDESC/CCL/issues/553

In the end I was actually happy to simplify the C layer by doing this, but I do agree that this operation is ubiquitous enough that having a convenience sampler-interpolator would be useful. I propose that we do that in the python layer after the generalized tracers PR gets merged. (I'm really, really close, I promise)

**Comment by beckermr** [comment] 2019-06-26 00:21
I’m suggesting people use this https://docs.scipy.org/doc/scipy/reference/interpolate.html

The issue with a canned interpolant is that the number of points etc is depend upon the accuracy requirements the user has which we don’t know a prior. Further, when using the angular cls to make real space xi’s, ccl will rebuild the interpolant anyways.

**Comment by slosar** [comment] 2019-06-26 20:29
But my point is that you are forcing users to play with number of samples until the problem converges for their particular use. I would like at least this piece to be handed by CCL. I agree that interpolator goes to the python layer. And possibility would be to call angular_cl_setup_interpolator(lmin, lmax, accuracy) and then call angular_cl_interpolator to do it. Or something like that, no?

**Comment by beckermr** [comment] 2019-06-26 20:38
I see what you are saying. 

However, I am not sure we want to support code that does this kind of work for people in the long term. It is very hard to make an API promise that when a user says I want fractional accuracy of X%, we can actually write a function that will build an interpolant that will always meet that requirement. Further, it is unclear how general we expect our current set of benchmarks to be in terms of accuracy for models well outside the ones we have tested. 

Thus in my opinion forcing users to muck and make sure they have what they need is a feature, not a bug, so to say. 

If we do want to go this route, I suggest we build an adaptive interpolator that uses nested sets of points to estimate the error and refine the interpolant in regions where the error is too big. Happy to share more on how this might work.

**Comment by slosar** [comment] 2019-06-27 10:03
Fundamentally it is up to the CCL team to decide where does their scope ends. I still think that you could build some default interpolator which you would guarantee at Planck18 and then it is up  to users to spot-check for their problem -- I'm sure that that it will be satisfactory in 99% of practical uses.

**Comment by damonge** [comment] 2019-06-27 10:07
I'd vote for adding a small interpolator somewhere with lots of warnings in the documentation about having to check etc. For most intents and purposes (given how featureless the LSS/WL spectra are), anything that isn't too silly will be fine.

This can be done in the python layer now that we've freed ourselves from the C API, so it could be a 10-line piece of code

**Comment by damonge** [comment] 2019-06-27 10:09
I would imagine passing an interpolator object as an optional parameter to `ccl.angular_cl`. If that parameter is `None`, then it'll just compute everything at the input ells. Otherwise the interpolator sets the ells at which the computation happens and then interpolates back to the input ones.

**Comment by slosar** [comment] 2019-06-27 11:25
perfect.

**Comment by beckermr** [comment] 2019-06-27 11:48
Works for me!

**Comment by beckermr** [comment] 2019-09-18 12:17
In the interest of shipping v2 sooner rather than later, I am going to punt on this issue. Implementation post v2 would not break the API.

**Comment by c-d-leonard** [comment] 2020-03-20 13:06
How pressing do people feel this issue is at this stage? Is this something we want to push through before tagging v3?

**Comment by damonge** [comment] 2020-03-20 13:54
I think we should explore this before v3.

**Comment by slosar** [comment] 2020-03-22 23:01
I agree with David!

**Comment by damonge** [comment] 2022-08-05 16:48
Since the title of this issue has nothing to do with the actual action item here, I'm gonna close it and will open a new one that better describes what we're trying to accomplish.

**Closed by damonge** 2022-08-05 16:48 UTC
Labels: Enhancement, Optimization
