### ISSUE TITLE
problem setting FFTWDIR

### ISSUE THREAD

**Issue by johannct** [LSSTDESC/CCL#646] opened 2019-07-22 10:43 UTC
This env variable is supposed to be taken into account here
https://github.com/LSSTDESC/CCL/blob/6b8f0af672098e55c151b53c9a53789de46d7176/cmake/Modules/FindFFTW.cmake#L20
in order to let the user provide a path to an existing FFTW installation. I am using cmake 3.14.5 and this does not work : ENV(FFTWDIR) is not properly evaluated in the condition, as a result FFTW_INCLUDES is found as `/usr/include` which confirms that FFTWDIR was not taken into account. The following change (explicit evaluation of the env var) works for me:

> [tanugi@cca001 build]$ git diff ../cmake/Modules/FindFFTW.cmake 
diff --git a/cmake/Modules/FindFFTW.cmake b/cmake/Modules/FindFFTW.cmake
index f885438..d82ed98 100644
--- a/cmake/Modules/FindFFTW.cmake
+++ b/cmake/Modules/FindFFTW.cmake
@@ -17,7 +17,7 @@
\ #
 include(FindPkgConfig)
 #If environment variable FFTWDIR is specified, it has same effect as FFTW_ROOT
-if( NOT FFTW_ROOT AND ENV{FFTWDIR} )
+if( NOT FFTW_ROOT AND NOT "$ENV{FFTWDIR}" STREQUAL "")
   set( FFTW_ROOT $ENV{FFTWDIR} )
 endif()
 \# Check if we can use PkgConfig

**Comment by johannct** [comment] 2019-07-22 11:34
Then of course ANGPOW compilation also fails as it downloads https://github.com/LSSTDESC/Angpow4CCL/blob/master/cmake/Modules/FindFFTW.cmake which has the same problematic line for me.

**Comment by elisachisari** [comment] 2019-11-19 20:33
@johannct could you see if this happens again for you with the new CCL v2? Note angpow is temporarily deprecated in this version. Docs for installing v2 are here: https://ccl.readthedocs.io/en/v2.0.0/source/installation.html

**Comment by c-d-leonard** [comment] 2020-03-20 13:02
@johannct any update on this?

**Comment by damonge** [comment] 2022-08-05 16:50
OK, last chance! We'll close this in a few days unless someone tells us not to!

**Comment by nikfilippas** [comment] 2023-03-27 01:10
Closing this as stale/couldn't reproduce. Feel free to reopen if this problem ever appears again.

**Comment by nikfilippas** [comment] 2023-03-27 01:10
Closing this as stale/couldn't reproduce. Feel free to reopen if this problem ever appears again.

**Closed by nikfilippas** 2023-03-27 01:10 UTC
Labels: Installation
